export const books = [
    {
        title: "Guia para a Vida",
        author: "Evandro Guedes",
        year: 2019,
        avatar: `<img src="./images/guia_para_a_vida.jpg" alt="Livro Guia para a vida - Evandro Guedes"/>`,
    },
    {
        title: "Alô Você! Conquiste Seu Lugar",
        author: "Evandro Guedes",
        year: 2016,
        avatar: `<img src="./images/alo_voce.jpg" alt="Livro Alô Você! Conquiste Seu Lugar - Evandro Guedes"/>`,
    },
    {
        title: "O Segredo do Enriquecimento",
        author: "Evandro Guedes",
        year: 2019,
        avatar: `<img src="./images/o_segredo_do_enriquecimento.jpg" alt="O Segredo do Enriquecimento - Evandro Guedes"/>`,
    },
    {
        title: "Mais Esperto que o Diabo",
        author: "Napoleon Hill",
        year: 2014,
        avatar: `<img src="./images/mais_esperto_que_o_diabo.jpg" alt="Livro Mais Esperto que o Diabo - Napoleon Hill"/>`,
    },
    {
        title: "O Poder do Hábito",
        author: "Charles Duhigg",
        year: 2012,
        avatar: `<img src="./images/o_poder_do_habito.jpg" alt="Livro O Poder do Hábito - Charles Duhigg"/>`,
    },
    {
        title: "Geração de Valor",
        author: "Flávio Augusto",
        year: 2014,
        avatar: `<img src="./images/geracao_de_valor.jpg" alt="Livro Geração de Valor - Flávio Augusto"/>`,
    },
    {
        title: "Geração de Valor 2",
        author: "Flávio Augusto",
        year: 2014,
        avatar: `<img src="./images/geracao_de_valor_2.jpg" alt="Livro Geração de Valor 2 - Flávio Augusto"/>`,
    },
    {
        title: "Geração de Valor 3",
        author: "Flávio Augusto",
        year: 2015,
        avatar: `<img src="./images/geracao_de_valor_3.jpg" alt="Livro Geração de Valor 3 - Flávio Augusto"/>`,
    },
    {
        title: "Mindset",
        author: "Carol Dweck",
        year: 2017,
        avatar: `<img src="./images/mindset.jpg" alt="Livro Mindset - Carol Dweck"/>`,
    },
    {
        title: "Os 7 hábitos das Pessoas Altamente Eficazes",
        author: "Stephen Covey",
        year: 2017,
        avatar: `<img src="./images/os_7_habitos_das_pessoas_altamente_eficazes.jpg" alt="Livro Os 7 hábitos das Pessoas Altamente Eficazes - Stephen Covey"/>`,
    },
    {
        title: "Casais Inteligentes Enriquecem Juntos",
        author: "Gustavo Cerbasi",
        year: 2014,
        avatar: `<img src="./images/casais_inteligentes_enriquecem_juntos.jpg" alt="Livro Casais Inteligentes Enriquecem Juntos - Gustavo Cerbasi"/>`,
    },
    {
        title: "Na Raça: como Guilherme Benchimol criou a XP e iniciou a maior revolução do mercado financeiro brasileiro",
        author: "Maria Luíza Filgueiras",
        year: 2019,
        avatar: `<img src="./images/na_raca.jpg" alt="Livro Na Raça - Maria Luíza Filgueiras"/>`,
    },
    {
        title: "Quem mexeu no meu queijo?",
        author: "Spencer Johnson",
        year: 2017,
        avatar: `<img src="./images/quem_mexeu_no_meu_queijo.jpg" alt="Livro Quem mexeu no meu queijo? - Spencer Johnson"/>`,
    },
    {
        title: "O Homem Mais Rico da Babilônia",
        author: "George S. Clason",
        year: 2017,
        avatar: `<img src="./images/o_homem_mais_rico_da_babilonia.jpg" alt="Livro O Homem Mais Rico da Babilônia - George S. Clason"/>`,
    },
    {
        title: "Vencedoras por Opção (Great by Choice)",
        author: "Jim Collins e Mortem T. Hansen",
        year: 2018,
        avatar: `<img src="./images/vencedoras_por_opcao.jpg" alt="Livro Vencedoras por Opção - Jim Collins e Mortem T. Hansen"/>`,
    },
    {
        title: "Comece pelo porquê: como grandes líderes inspiram pessoas e equipes a agir",
        author: "Simon Sinek",
        year: 2018,
        avatar: `<img src="./images/comece_pelo_porque.jpg" alt="Livro Comece pelo porquê - Simon Sinek"/>`,
    },
    {
        title: "Quem Pensa Enriquece: edição oficial e original de 1937",
        author: "Napoleon Hill",
        year: 2020,
        avatar: `<img src="./images/quem_pensa_enriquece.jpg" alt="Livro Quem Pensa Enriquece - Napoleon Hill"/>`,
    },
    {
        title: "O Milagre da Manhã",
        author: "Hal Elrod",
        year: 2016,
        avatar: `<img src="./images/o_milagre_da_manha.jpg" alt="Livro O Milagre da Manhã - Hal Elrod"/>`,
    },
    {
        title: "Comunicação não-violenta: técnicas para aprimorar relacionamentos pessoais e profissionais",
        author: "Marshall Rosenberg",
        year: 2006,
        avatar: `<img src="./images/comunicacao_nao_violenta.jpg" alt="Livro Comunicação não-violenta - Marshall Rosenberg"/>`,
    },
    {
        title: "Esteja, viva, permaneça 100% Presente: o poder da disciplina, do foco e dos minihábitos para conseguir realizar seu potencial máximo",
        author: "Joel Jota",
        year: 2019,
        avatar: `<img src="./images/100_presente.jpg" alt="Livro 100% Presente - Joel Jota"/>`,
    },
    {
        title: "A Arte da Guerra",
        author: "Sun Tzu",
        year: 2018,
        avatar: `<img src="./images/a_arte_da_guerra.jpg" alt="Livro A Arte da Guerra - Sun Tzu"/>`,
    },
    {
        title: "A História do Mundo para quem tem pressa",
        author: "Emma Marriot",
        year: 2015,
        avatar: `<img src="./images/a_historia_do_mundo_pra_quem_tem_pressa.jpg" alt="Livro A  História do Mundo para quem tem pressa - Emma Marriot"/>`,
    },
    {
        title: "As cartas de Bezos - 14 princípios para crescer como a Amazon",
        author: "Steve Anderson",
        year: 2020,
        avatar: `<img src="./images/as_cartas_de_bezos.jpg" alt="Livro As cartas de Bezos - Steve Anderson"/>`,
    },
    {
        title: "A loja de tudo - Exclusivo Amazon",
        author: "Brad Stone",
        year: 2019,
        avatar: `<img src="./images/a_loja_de_tudo.jpg" alt="Livro A loja de tudo - Brad Stone"/>`,
    },
    {
        title: "Essencialismo",
        author: "Greg Mckeown",
        year: 2015,
        avatar: `<img src="./images/essencialismo.jpg" alt="Livro Essencialismo - Greg Mckeown"/>`,
    },
    {
        title: "Fora de Série - Outliers",
        author: "Malcolm Gladwell",
        year: 2011,
        avatar: `<img src="./images/fora_de_serie_outliers.jpg" alt="Livro Fora de Série - Outliers - Malcolm Gladwell"/>`,
    },
    {
        title: "A revolução dos bichos: um conto de fadas",
        author: "George Orwell",
        year: 2007,
        avatar: `<img src="./images/a_revolucao_dos_bichos.jpg" alt="Livro A revolução dos bichos - George Orwell"/>`,
    },
    {
        title: "Descubra seus pontos fortes 2.0",
        author: "Don Clifton e Tom Rath",
        year: 2019,
        avatar: `<img src="./images/descubra_seus_pontos_fortes.jpg" alt="Livro Descubra seus pontos fortes 2.0 - Don Clifton e Tom Rath"/>`,
    },
    {
        title: "A Única Coisa: a verdade surpreendentemente simples por trás de resultados extraordinários",
        author: "Gary Keller e Jay Papasan",
        year: 2021,
        avatar: `<img src="./images/a_unica_coisa.jpg" alt="Livro A Única Coisa - Gary Keller e Jay Papasan"/>`,
    },
    {
        title: "Ultracorajoso",
        author: "Joel Jota",
        year: 2021,
        avatar: `<img src="./images/ultracorajoso.jpg" alt="Livro Ultracorajoso - Joel Jota"/>`,
    },
    {
        title: "Política é Para Todos",
        author: "Gabriela Prioli",
        year: 2021,
        avatar: `<img src="./images/politica_e_para_todos.jpg" alt="Livro Política é Para Todos - Gabriela Prioli"/>`,
    },
    {
        title: "Do Mil ao Milhão. Sem cortar o Cafezinho",
        author: "Thiago Nigro",
        year: 2018,
        avatar: `<img src="./images/do_mil_ao_milhao.jpg" alt="Livro Do Mil ao Milhão - Thiago Nigro"/>`,
    },
    {
        title: "Sonho Grande: como Jorge Paulo Lemann, Marcel Telles e Beto Sicupira revolucionaram o capitalismo brasileiro e conquistaram o mundo",
        author: "Cristiane Correa",
        year: 2013,
        avatar: `<img src="./images/sonho_grande.jpg" alt="Livro Sonho Grande - Cristiane Correa"/>`,
    },
    {
        title: "O Poder da Ação",
        author: "Paulo Vieira",
        year: 2015,
        avatar: `<img src="./images/o_poder_da_acao.jpg" alt="Livro O Poder da Ação - Paulo Vieira"/>`,
    },
];